layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  sort_by options:
    - pushed
    - stars
  limit: 9
  exclude:
    forks: false
    projects:
    - netlob.app
    - lingo-online
    - roostersb
    - Peppels.js
    - stuk
    - requestify
    - pew
    - SpigotREST
  #   - P5-Pong
  #   - kajmunk-stats
  #   - gps
  #   - Magiscord
  # include:
  #   - mamorgen/magiscore
  #   - magiscore
  #   - simplyGits/MagisterJS
  #   - MagisterJS

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  linkedin: sjoerdbolten
  # medium: @your_username
  stackoverflow: 9107414
  # telegram: your_username
  twitter: netlob
  youtube: UCtFYDZCzHBmBLML1Lyvfcrw
  instagram: sjoerd.netlob
  # unsplash: your_username
  # vk: your_username
  website: https://netlob.app

topics:
  - name: NodeJS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/nodejs/nodejs.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/typescript/typescript.png
    
  - name: GraphQL
    web_url: https://github.com/topics/GraphQL
    image_url: https://raw.githubusercontent.com/github/explore/5c058a388828bb5fde0bcafd4bc867b5bb3f26f3/topics/graphql/graphql.png

  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/angular/angular.png

  - name: Vue
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/vue/vue.png
